# docker-compose.yml
version: "3"

services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - ./client:/app
            - /app/node_modules
        ports:
            - "3000:3000"
        depends_on:
            - server

    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        volumes:
            - ./server:/app
            - /app/node_modules
        ports:
            - "4000:4000"
